// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0L8Iwvq9V6t4AghRxmIkOh19D0qSWS0',
    appId: '1:1074817937264:web:7d94085e2bcebacca669b5',
    messagingSenderId: '1074817937264',
    projectId: 'spit-canteen',
    authDomain: 'spit-canteen.firebaseapp.com',
    storageBucket: 'spit-canteen.firebasestorage.app',
    measurementId: 'G-0BBFZ8HW9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBChGSfb80yhDmOrKYBSn2Ld17HQ7TqZv4',
    appId: '1:1074817937264:android:b7a1892cf318eb4ca669b5',
    messagingSenderId: '1074817937264',
    projectId: 'spit-canteen',
    storageBucket: 'spit-canteen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrWnfgW2hl1qo-BqujzjE7cffdkgis4Q',
    appId: '1:1074817937264:ios:3e709848c56484e6a669b5',
    messagingSenderId: '1074817937264',
    projectId: 'spit-canteen',
    storageBucket: 'spit-canteen.firebasestorage.app',
    iosBundleId: 'com.example.canteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrWnfgW2hl1qo-BqujzjE7cffdkgis4Q',
    appId: '1:1074817937264:ios:3e709848c56484e6a669b5',
    messagingSenderId: '1074817937264',
    projectId: 'spit-canteen',
    storageBucket: 'spit-canteen.firebasestorage.app',
    iosBundleId: 'com.example.canteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD0L8Iwvq9V6t4AghRxmIkOh19D0qSWS0',
    appId: '1:1074817937264:web:01c60702fcb039d4a669b5',
    messagingSenderId: '1074817937264',
    projectId: 'spit-canteen',
    authDomain: 'spit-canteen.firebaseapp.com',
    storageBucket: 'spit-canteen.firebasestorage.app',
    measurementId: 'G-2S9V4ZEV9Z',
  );
}
